# Generated by Django 5.2.7 on 2025-10-30 18:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('region_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('core_generic_created_at', models.DateTimeField(auto_now_add=True, db_column='CORE_GENERIC_CREATED_AT', null=True)),
                ('core_generic_updated_at', models.DateTimeField(auto_now=True, db_column='CORE_GENERIC_UPDATED_AT', null=True)),
                ('id', models.UUIDField(db_column='USER_ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, db_column='USERNAME', max_length=100, null=True)),
                ('first_name', models.CharField(db_column='FIRST_NAME', max_length=50)),
                ('last_name', models.CharField(db_column='LAST_NAME', max_length=50)),
                ('email', models.EmailField(db_column='EMAIL', max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, db_column='PHONE_NUMBER', max_length=15, null=True)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('is_staff', models.BooleanField(db_column='IS_STAFF', default=False)),
                ('is_superuser', models.BooleanField(db_column='IS_SUPERUSER', default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_generic_created_at', models.DateTimeField(auto_now_add=True, db_column='CORE_GENERIC_CREATED_AT', null=True)),
                ('core_generic_updated_at', models.DateTimeField(auto_now=True, db_column='CORE_GENERIC_UPDATED_AT', null=True)),
                ('profile_photo', models.URLField(blank=True, db_column='PROFILE_PHOTO', max_length=100, null=True)),
                ('address', models.CharField(db_column='ADDRESS', max_length=255)),
                ('postal_code', models.CharField(db_column='POSTAL_CODE', max_length=10)),
                ('emergency_contact_number', models.CharField(blank=True, db_column='EMERGENCY_CONTACT_NUMBER', max_length=15, null=True)),
                ('city', models.ForeignKey(blank=True, db_column='CITY_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserDetailModel_city', to='region_data.citymodel')),
                ('core_generic_created_by', models.ForeignKey(blank=True, db_column='CORE_GENERIC_CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user_auth.userdetailmodel')),
                ('core_generic_updated_by', models.ForeignKey(blank=True, db_column='CORE_GENERIC_UPDATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user_auth.userdetailmodel')),
                ('country', models.ForeignKey(blank=True, db_column='COUNTRY_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserDetailModel_country', to='region_data.countrymodel')),
                ('state', models.ForeignKey(blank=True, db_column='STATE_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserDetailModel_state', to='region_data.statemodel')),
                ('user', models.OneToOneField(db_column='USER_DETAIL_ID', on_delete=django.db.models.deletion.CASCADE, related_name='UserDetailModel_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='usermodel',
            name='core_generic_created_by',
            field=models.ForeignKey(blank=True, db_column='CORE_GENERIC_CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user_auth.userdetailmodel'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='core_generic_updated_by',
            field=models.ForeignKey(blank=True, db_column='CORE_GENERIC_UPDATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user_auth.userdetailmodel'),
        ),
        migrations.CreateModel(
            name='UserRoleModel',
            fields=[
                ('core_generic_created_at', models.DateTimeField(auto_now_add=True, db_column='CORE_GENERIC_CREATED_AT', null=True)),
                ('core_generic_updated_at', models.DateTimeField(auto_now=True, db_column='CORE_GENERIC_UPDATED_AT', null=True)),
                ('id', models.UUIDField(db_column='USER_ROLE_ID', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='TITLE', max_length=100, null=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('TENANT', 'Tenant'), ('MANAGER', 'Manager')], db_column='ROLE', max_length=50)),
                ('core_generic_created_by', models.ForeignKey(blank=True, db_column='CORE_GENERIC_CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user_auth.userdetailmodel')),
                ('core_generic_updated_by', models.ForeignKey(blank=True, db_column='CORE_GENERIC_UPDATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user_auth.userdetailmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_role',
            field=models.ForeignKey(db_column='USER_ROLE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='UserModel_user_role', to='user_auth.userrolemodel'),
        ),
    ]
