# Generated by Django 5.2.7 on 2025-10-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('core_generic_created_at', models.DateTimeField(auto_now_add=True, db_column='CORE_GENERIC_CREATED_AT', null=True)),
                ('core_generic_updated_at', models.DateTimeField(auto_now=True, db_column='CORE_GENERIC_UPDATED_AT', null=True)),
                ('id', models.BigAutoField(db_column='CITY_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='CITY_NAME', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('core_generic_created_at', models.DateTimeField(auto_now_add=True, db_column='CORE_GENERIC_CREATED_AT', null=True)),
                ('core_generic_updated_at', models.DateTimeField(auto_now=True, db_column='CORE_GENERIC_UPDATED_AT', null=True)),
                ('id', models.BigAutoField(db_column='COUNTRY_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='COUNTRY_NAME', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('core_generic_created_at', models.DateTimeField(auto_now_add=True, db_column='CORE_GENERIC_CREATED_AT', null=True)),
                ('core_generic_updated_at', models.DateTimeField(auto_now=True, db_column='CORE_GENERIC_UPDATED_AT', null=True)),
                ('id', models.BigAutoField(db_column='STATE_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='STATE_NAME', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
