# Generated by Django 5.2.7 on 2025-10-30 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region_data', '0001_initial'),
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymodel',
            name='core_generic_created_by',
            field=models.ForeignKey(blank=True, db_column='CORE_GENERIC_CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user_auth.userdetailmodel'),
        ),
        migrations.AddField(
            model_name='citymodel',
            name='core_generic_updated_by',
            field=models.ForeignKey(blank=True, db_column='CORE_GENERIC_UPDATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user_auth.userdetailmodel'),
        ),
        migrations.AddField(
            model_name='countrymodel',
            name='core_generic_created_by',
            field=models.ForeignKey(blank=True, db_column='CORE_GENERIC_CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user_auth.userdetailmodel'),
        ),
        migrations.AddField(
            model_name='countrymodel',
            name='core_generic_updated_by',
            field=models.ForeignKey(blank=True, db_column='CORE_GENERIC_UPDATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user_auth.userdetailmodel'),
        ),
        migrations.AddField(
            model_name='citymodel',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CityModel_country', to='region_data.countrymodel'),
        ),
        migrations.AddField(
            model_name='statemodel',
            name='core_generic_created_by',
            field=models.ForeignKey(blank=True, db_column='CORE_GENERIC_CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user_auth.userdetailmodel'),
        ),
        migrations.AddField(
            model_name='statemodel',
            name='core_generic_updated_by',
            field=models.ForeignKey(blank=True, db_column='CORE_GENERIC_UPDATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user_auth.userdetailmodel'),
        ),
        migrations.AddField(
            model_name='statemodel',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StateModel_country', to='region_data.countrymodel'),
        ),
        migrations.AddField(
            model_name='citymodel',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CityModel_state', to='region_data.statemodel'),
        ),
    ]
