# Generated by Django 5.2.7 on 2025-10-30 18:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListTokenModel',
            fields=[
                ('core_generic_created_at', models.DateTimeField(auto_now_add=True, db_column='CORE_GENERIC_CREATED_AT', null=True)),
                ('core_generic_updated_at', models.DateTimeField(auto_now=True, db_column='CORE_GENERIC_UPDATED_AT', null=True)),
                ('id', models.UUIDField(db_column='BLACK_LIST_TOKEN_ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.TextField(db_column='JWT_TOKEN')),
                ('is_login', models.BooleanField(db_column='IS_LOGIN', default=False)),
                ('is_delete', models.BooleanField(db_column='IS_DELETE', default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
