# Generated by Django 5.2.7 on 2025-10-30 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('user_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklisttokenmodel',
            name='core_generic_created_by',
            field=models.ForeignKey(blank=True, db_column='CORE_GENERIC_CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user_auth.userdetailmodel'),
        ),
        migrations.AddField(
            model_name='blacklisttokenmodel',
            name='core_generic_updated_by',
            field=models.ForeignKey(blank=True, db_column='CORE_GENERIC_UPDATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user_auth.userdetailmodel'),
        ),
        migrations.AddField(
            model_name='blacklisttokenmodel',
            name='user',
            field=models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='BlackListTokenModel_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
